Repository kowainik/smuggler, pull requests merged in 2018-10, with the labels that each got.

#46 [#45] Fix stack.yaml
  stack-mac-8.6.1.yaml
Labels: Hacktoberfest, bug

#48 [#47] Add stack extra deps
  .travis.yml
  README.md
  stack-mac-8.6.1.yaml
  stack.yaml
Labels: CI, Hacktoberfest

#55 Improve test output
  smuggler.cabal
  test/Test.hs
Labels: Hacktoberfest, test

#51 [#30] Optimize the whole import deletion
  src/Smuggler/Plugin.hs
Labels: Hacktoberfest, performance, purify

#58 Add tests for implicit imports
  smuggler.cabal
  test/Test/ImplicitImportUnused.golden
  test/Test/ImplicitImportUnused.hs
  test/Test/ImplicitImportUsed.golden
  test/Test/ImplicitImportUsed.hs
Labels: Hacktoberfest, test

#61 Remove trailing commas
  smuggler.cabal
  src/Smuggler/Anns.hs
  src/Smuggler/Plugin.hs
  test/Test/BoolPartlyUsedFirst.golden
  test/Test/TypeConstructorUnusedComma.golden
  test/Test/TypeConstructorUnusedComma.hs
  test/Test/TypeUsed.golden
Labels: Hacktoberfest, enhancement, ghc-api, purify
