Repository kowainik/smuggler, pull requests merged in 2018-07, with the labels that each got.

#18 [#17] Add basic source plugin example
  app/Main.hs
  cabal.project
  smuggler.cabal
  src/Prelude.txt
  src/Smuggler/Plugin.hs
Labels: ghc-api

#20 [#19] Introduce simple function which prints sources of the module
  app/Main.hs
  smuggler.cabal
  src/Smuggler/Plugin.hs
Labels: ghc-api

#22 [#21] Use ghc-exactprint to parse and output module
  .gitignore
  README.md
  cabal.project
  smuggler.cabal
  src/Smuggler/Parser.hs
  src/Smuggler/Plugin.hs
Labels: ghc-api, purify

#26 [#24] Add file hashes with hash-store
  .gitignore
  cabal.project
  smuggler.cabal
  src/Smuggler.hs
  src/Smuggler/Plugin.hs
Labels: ghc-api, purify

#27 [#25] Remove unused imports
  app/Main.hs
  smuggler.cabal
  src/Smuggler/Debug.hs
  src/Smuggler/Plugin.hs
Labels: purify

#32 Refactor plugin slightly
  src/Smuggler/Plugin.hs
Labels: refactoring

#33 [#31] Do nothing on parse errors
  README.md
  smuggler.cabal
  src/Prelude.txt
  src/Smuggler/Parser.hs
  src/Smuggler/Plugin.hs
Labels: doc, enhancement, refactoring

#34 [#23] Add basic golden tests
  .gitignore
  smuggler.cabal
  src/Smuggler/Plugin.hs
  stack-alpha.yaml
  test/Spec.hs
  test/Test.hs
  test/Test/BoolBoolUnused.golden
  test/Test/BoolBoolUnused.hs
  test/Test/BoolBoolUsed.golden
  test/Test/BoolBoolUsed.hs
  test/Test/BoolPartlyUsedFirst.golden
  test/Test/BoolPartlyUsedFirst.hs
  test/Test/BoolPartlyUsedLast.golden
  test/Test/BoolPartlyUsedLast.hs
  test/Test/Dummy.golden
  test/Test/Dummy.hs
  test/Test/ImportEmpty.golden
  test/Test/ImportEmpty.hs
  test/Test/TypeConstructorUnused.golden
  test/Test/TypeConstructorUnused.hs
  test/Test/TypeConstructorUsed.golden
  test/Test/TypeConstructorUsed.hs
  test/Test/TypeUnused.golden
  test/Test/TypeUnused.hs
  test/Test/TypeUsed.golden
  test/Test/TypeUsed.hs
Labels: test

#36 [#35] Add proper travis
  .travis.yml
Labels: CI

#37 [#28] Remove multiline imports
  smuggler.cabal
  src/Smuggler/Plugin.hs
  test/Test/MultilineUnused.golden
  test/Test/MultilineUnused.hs
Labels: enhancement, purify

#40 Add tests for wildcard imports
  smuggler.cabal
  test/Test/WildcardUnused.golden
  test/Test/WildcardUnused.hs
  test/Test/WildcardUsed.golden
  test/Test/WildcardUsed.hs
Labels: test
