Repository kowainik/smuggler, pull requests merged in 2018-06, with the labels that each got.

#6 [#4] Impl removeAnnAtLoc
  smuggler.cabal
  src/Smuggler/Anns.hs
  src/Smuggler/Parser.hs
  test/input.hs
Labels: purify

#10 [#3] Extract all OccName's from module body
  smuggler.cabal
  src/Smuggler/Name.hs
  src/Smuggler/Parser.hs
  test/input.hs
Labels: ghc-api

#12 [#8] Function to get map from HSModule
  smuggler.cabal
  src/Smuggler/Import.hs
  src/Smuggler/Loc.hs
  src/Smuggler/Parser.hs
  test/input.hs
Labels: ghc-api, purify
